baseURL = 'https://64ef6981cd280e0008902e4f--tourmaline-centaur-de5301.netlify.app/'
languageCode = 'en-us'
theme = 'terminal'
enableEmoji = true
enableRobotsTXT = true
sectionPagesMenu = 'main'
configDir = "root/"

[params]
title = "HappyHacker22's Blog"
author = "HappyHacker22"
description = "My personal blog site in my career"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blogs"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "learn"
    name = "Roadmap"
    url = "/roadmaps"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "zkp"
    name = "ZKP"
    url = "/zkp"
    weight = 10