baseURL = 'https://tourmaline-centaur-de5301.netlify.app//'
languageCode = 'en-us'
theme = 'terminal'
enableEmoji = true
enableRobotsTXT = true
sectionPagesMenu = 'main'
configDir = "root/"

[params]
title = "HappyHacker22's Blog"
author = "HappyHacker22"
description = "My personal blog site in my career"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blogs"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "learn"
    name = "Roadmap"
    url = "/roadmaps"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "zkp"
    name = "ZKP"
    url = "/zkp"
    weight = 10

  [[menu.main]]
    identifier = "Crypto (Hoffstein)"
    name = "Crypto (Hoffstein)"
    url = "/crypto_hoffstein"
    weight = 5

  [[menu.main]]
    identifier = "Crypto (Lindell)"
    name = "Crypto (Lindell)"
    url = "/crypto_lindell"
    weight = 5

  [[menu.main]]
    identifier = "Image Processing and Computer Vision"
    name = "Image Processing and Computer Vision"
    url = "digital_image_processing_and_computer_vision/"
    weigt = 10