baseURL = 'https://happyhacker22.github.io/'
languageCode = 'en-us'
theme = 'terminal'
enableEmoji = true
enableRobotsTXT = true
sectionPagesMenu = 'main'

[params]
title = "HappyHacker22's Blog"
author = "HappyHacker22"
description = "My personal blog site in my career"